/*
 * Copyright (C) Frickly Systems GmbH
 * Copyright (C) MBition GmbH
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// Defines for Power I/O Shield hardware pin mapping

#define POWER_IO_SHIELD_OUTPUT_PINS_START 2
#define POWER_IO_SHIELD_OUTPUT_PINS_MASK \
  (0x3F << POWER_IO_SHIELD_OUTPUT_PINS_START)

#define POWER_IO_SHIELD_INPUT_PINS_START 8
#define POWER_IO_SHIELD_INPUT_PINS_MASK \
  (0x3F << POWER_IO_SHIELD_INPUT_PINS_START)

#define POWER_IO_SHIELD_FAULT0_PIN 14
#define POWER_IO_SHIELD_FAULT1_PIN 0
#define POWER_IO_SHIELD_FAULT2_PIN 1

#define POWER_IO_SHIELD_HARD_INVERT_PINS POWER_IO_SHIELD_INPUT_PINS_MASK
