name: Pylint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        working-directory: scripts
        run: |
          pip3 install -r requirements.txt
          pip3 install pylint west
          pylint --disable=R,C **/*.py